### ISSUE TITLE
MacOS implementation is not thread-safe

### ISSUE THREAD

**Issue by roblabla** [Speedy37/mountpoints-rs#3]
While reviewing this crate, I saw that the MacOS implementation uses `getmntinfo`, which has the following warning in the man:

> The `getmntinfo()` function maintains ownership of the results buffer it allocates, and may overwrite or free this buffer in subsequent calls to `getmntinfo()`.  For this reason, `getmntinfo()` is not thread-safe.

As such, I believe that this crate is not thread-safe: Using `mountinfos()` from multiple threads could result in a crash.

I think the proper solution is to change this code to either use `getmntinfo_r_np` (available since MacOS 10.13) or `getfsstat` (available on every version of MacOS AFAIK? It's part of BSD 4.4).

**Comment by Speedy37** [comment]
Good catch

I just put a few links for myself to help me do the patch:
https://github.com/apple/darwin-xnu/blob/main/bsd/sys/mount.h
https://github.com/apple/darwin-xnu/blob/main/bsd/sys/cdefs.h
```c
int     getmntinfo_r_np(struct statfs **, int) __DARWIN_INODE64(getmntinfo_r_np)
#define __DARWIN_INODE64(sym)           __asm("_" __STRING(sym) __DARWIN_SUF_64_BIT_INO_T)

```
